#! /usr/bin/env perl 
use warnings;
use strict;
use File::Path qw(make_path);

my $vjf_dir = "/opt/vjf";
my $git_bin = "/usr/bin/git";

my $first_sleep_time = 60 * 5;
my $normal_sleep_time = 60 * 60;

sub update() {


}

sub check_requirements() {
    die "git is not installed or I lack permissions" unless ( -x $git_bin);

    unless ( -w $vjf_dir ) {
        make_path("$vjf_dir") or die "Failed creating $vjf_dir"
    }
}

check_requirements();
sleep($first_sleep_time);
while (1) {
    update();
    sleep($normal_sleep_time);
}
