#!/usr/bin/zsh

git_src_dir="/usr/src/vjf"
vjf_dir="/usr/local/vjf"
vjf_src_dir="${git_src_dir}${vjf_dir}"
git_old_dir="/usr/src/vjfold";
git_url="git@bitbucket.org:vjf/themis.git"
ERROR_FILE_PERMS=16
ERROR_GIT_CLONE=32

if [[ -x /usr/bin/git ]]; then
        # this feels bad :(
        if [[ -d "$git_src_dir" ]]; then
            rm -r "$git_old_dir"
            mv "$git_src_dir" "$git_old_dir"
        fi
        mkdir -p "$git_src_dir"
    if [[ -x "$git_src_dir" ]]; then
        # unfortunately dominik has the only key that is installed on every system
        # this deployment key is the only one that is allowed to pull from our bitbucket account
        chown :dominik "$git_src_dir"
        if [[ $? -ne 0 ]]; then; exit "$ERROR_FILE_PERMS"; fi
        chmod 775 "$git_src_dir"
        if [[ $? -ne 0 ]]; then; exit "$ERROR_FILE_PERMS"; fi
        # first hacky way to get bitbucket keys
        su dominik -c "ssh -o StrictHostKeyChecking=no bitbucket.org"  
        su dominik -c "git clone $git_url $git_src_dir" 
        if [[ $? -ne 0 ]]; then; exit "$ERROR_GIT_CLONE"; fi;
        if [[ ! -d "$vjf_dir" ]]; then 
            mkdir "$vjf_dir";
        fi;
        # everything should be owned by root
        chown -R root:root "$vjf_dir"
        [[ -x "$vjf_dir" ]] && 
        # we want no subfolder so we need the trailing /
        rsync --archive --delete --verbose "${vjf_src_dir}/" "$vjf_dir"
    else
        exit 1;
    fi;
fi;
