#!/usr/bin/zsh

git_src_dir="/usr/src/vjf"
vjf_dir="/usr/local/vjf"
vjf_src_dir="$git_src_dir/themis$vjf_dir"
git_old_dir="/usr/src/vjfold";
git_url="git@bitbucket.org:vjf/themis.git"
known_hosts="/home/dominik/.ssh/known_hosts"
ERROR_FILE_PERMS=16
ERROR_GIT_CLONE=32

if [[ -x /usr/bin/git ]]; then
        # this feels bad :(
        if [[ -d "$git_src_dir" ]]; then
            rm -r "$git_old_dir"
            mv "$git_src_dir" "$git_old_dir"
        fi
        mkdir -p "$git_src_dir"
    if [[ -x "$git_src_dir" ]]; then
        # unfortunately dominik has the only key that is installed on every system
        # this deployment key is the only one that is allowed to pull from our bitbucket account
        chown :dominik "$git_src_dir"
        if [[ $? -ne 0 ]]; then; exit "$ERROR_FILE_PERMS"; fi
        # import bitbucket keys
        # grep options: -q = quiet: nothing is written stdout, exist with 0 if a match is found - even on error
        #               -x = line-regexp: select only matches that exactly match the whole line
        if grep -qx "luP3aTsKaVWca8hpJIQTvKR5kJw=|Rr+QL8s+pxHkvHuB90ERfYZ6BsE=" "$known_hosts"; then
        else
           echo "|1|luP3aTsKaVWca8hpJIQTvKR5kJw=|Rr+QL8s+pxHkvHuB90ERfYZ6BsE= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
" >> "$known_hosts"
        fi
        if grep -Fqx "jU97LLcmvRgHYp5yvN3FUgWYjvY=|XvCssgWZHAZHy/n2MDFfKv4gbZM=" "$known_hosts"; then
        else
            echo "|1|jU97LLcmvRgHYp5yvN3FUgWYjvY=|XvCssgWZHAZHy/n2MDFfKv4gbZM= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
" >> "$known_hosts"
        fi
        su dominik -c "git clone $git_url $git_src_dir" 
        if [[ $? -ne 0 ]]; then; exit "$ERROR_GIT_CLONE"; fi;
        if [[ ! -d "$vjf_dir" ]]; then 
            mkdir "$vjf_dir";
        fi;
        [[ -x "$vjf_dir" ]] && 
        # we want no subfolder so we need the trailing /
        rsync --archive --delete --verbose "${vjf_src_dir}/" "$vjf_dir"
          
    else
        exit 1;
    fi;
fi;
